<!--Title Ends-->

<link href="assets/css/style.css" type="text/css" rel="stylesheet" media="screen">
</head>
<body>
<div id="page" class="container"><!--Page Start-->
    <header><!--Header Start-->
        <h1>Arrow Photography</h1>
        <nav>
            <ul>
                <li><a href="index.php">Home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Portfolio</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>
    </header><!--Header End-->

    <div id="content" class="container"><!--Content Start-->